create table produto (
    id              bigint        generated by default as identity primary key,
    nome            varchar(120)  not null,
    principio_ativo varchar(120)  not null,
    fabricante      varchar(120)  not null,
    codigo_barras   varchar(14)   not null,
    preco_venda     numeric(12, 2) not null,
    exigencia       varchar(20)   not null,
    estoque_minimo  integer       not null default 0,
    ativo           boolean       not null default true,
    constraint uk_produto_codigo_barras unique (codigo_barras),
    constraint ck_produto_preco_venda check (preco_venda >= 0),
    constraint ck_produto_estoque_minimo check (estoque_minimo >= 0),
    constraint ck_produto_exigencia check (
        exigencia in ('ISENTO', 'RECEITA_SIMPLES', 'RECEITA_RETIDA', 'CONTROLADO')
    )
);
