create table usuario (
    id         bigint       generated by default as identity primary key,
    nome       varchar(120) not null,
    email      varchar(150) not null unique,
    senha_hash varchar(255) not null,
    perfil     varchar(20)  not null,
    ativo      boolean      not null default true,
    criado_em  timestamp with time zone not null default now(),
    constraint ck_usuario_perfil check (perfil in ('ATENDENTE', 'FARMACEUTICO', 'GERENTE'))
);

-- Usuários de demonstração. Senha: farmalog123
insert into usuario (nome, email, senha_hash, perfil) values
    ('Gerente Demo',      'gerente@farmalog.dev',      '$2a$10$i3uJja/Cwr1pQxTy1SVg/utcGXn2yJvwknrhK5/y9xdeNHtgWZq6y', 'GERENTE'),
    ('Farmacêutico Demo', 'farmaceutico@farmalog.dev', '$2a$10$i3uJja/Cwr1pQxTy1SVg/utcGXn2yJvwknrhK5/y9xdeNHtgWZq6y', 'FARMACEUTICO'),
    ('Atendente Demo',    'atendente@farmalog.dev',    '$2a$10$i3uJja/Cwr1pQxTy1SVg/utcGXn2yJvwknrhK5/y9xdeNHtgWZq6y', 'ATENDENTE');
