create table lote (
    id               bigint         generated by default as identity primary key,
    produto_id       bigint         not null references produto (id),
    codigo           varchar(60)    not null,
    data_validade    date           not null,
    quantidade_atual integer        not null,
    preco_custo      numeric(12, 2) not null,
    data_entrada     date           not null,
    version          bigint         not null default 0,
    constraint uk_lote_produto_codigo unique (produto_id, codigo),
    constraint ck_lote_quantidade_atual check (quantidade_atual >= 0),
    constraint ck_lote_preco_custo check (preco_custo >= 0)
);

create table movimentacao_estoque (
    id         bigint      generated by default as identity primary key,
    lote_id    bigint      not null references lote (id),
    tipo       varchar(20) not null,
    quantidade integer     not null,
    usuario_id bigint      not null references usuario (id),
    data_hora  timestamp with time zone not null default now(),
    observacao varchar(255),
    constraint ck_mov_tipo check (tipo in ('ENTRADA', 'SAIDA_VENDA', 'ESTORNO', 'AJUSTE', 'DESCARTE')),
    constraint ck_mov_quantidade check (quantidade > 0)
);

create index ix_mov_lote on movimentacao_estoque (lote_id);
create index ix_mov_data_hora on movimentacao_estoque (data_hora);
