create table venda (
    id              bigint         generated by default as identity primary key,
    operador_id     bigint         not null references usuario (id),
    farmaceutico_id bigint         references usuario (id),
    cliente_cpf     varchar(11),
    data_hora       timestamp with time zone not null default now(),
    valor_total     numeric(12, 2) not null,
    status          varchar(20)    not null,
    constraint ck_venda_status      check (status in ('CONCLUIDA', 'CANCELADA')),
    constraint ck_venda_valor_total check (valor_total >= 0)
);

create table item_venda (
    id             bigint         generated by default as identity primary key,
    venda_id       bigint         not null references venda (id),
    produto_id     bigint         not null references produto (id),
    quantidade     integer        not null,
    preco_unitario numeric(12, 2) not null,
    subtotal       numeric(12, 2) not null,
    constraint ck_item_quantidade check (quantidade > 0)
);

create table receita (
    id              bigint      generated by default as identity primary key,
    venda_id        bigint      not null unique references venda (id),
    numero          varchar(60) not null,
    crm_medico      varchar(30) not null,
    data_emissao    date        not null,
    farmaceutico_id bigint      not null references usuario (id)
);

alter table movimentacao_estoque
    add column item_venda_id bigint references item_venda (id);

create index ix_venda_data_hora  on venda (data_hora);
create index ix_item_venda_venda on item_venda (venda_id);
create index ix_mov_item_venda   on movimentacao_estoque (item_venda_id);
